env_files = [".env"]

[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.build-dev]
private = true
command = "cargo"
args = ["build"]
condition = { profiles = ["development"] }
env = { "TARGET_DIR" = "debug"}

[tasks.build-release]
private = true
command = "cargo"
args = ["build", "--release"]
condition = { profiles = ["production"] }
env = { "TARGET_DIR" = "release"}

[tasks.build]
dependencies = ["build-dev", "build-release"]
script = { file = "build.sh" }

[tasks.run]
dependencies = ["build"]
command = "./dist/Applications/bw-ssh-agent.app/Contents/MacOS/bw-ssh-agent"
args = ["${@}"]

[tasks.clean]
command = "cargo"
args = ["clean"]