env_files = [".env"]

[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.build-app-dev]
dependencies = ["build"]
script = { file = "build.sh" }

[tasks.run]
dependencies = ["build-app-dev"]
command = "./dist/Applications/bw-ssh-agent.app/Contents/MacOS/bw-ssh-agent"
args = ["${@}"]

[tasks.clean]
command = "cargo"
args = ["clean"]